/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuessRouteRouteImport } from './routes/_guess/route'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as DemoDrizzleRouteImport } from './routes/demo/drizzle'
import { Route as AuthedCreateRouteImport } from './routes/_authed/create'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as GuessAuthRegisterRouteImport } from './routes/_guess/auth/register'
import { Route as GuessAuthLoginRouteImport } from './routes/_guess/auth/login'
import { Route as AuthedViewPromptIdRouteImport } from './routes/_authed/view.$promptId'
import { Route as AuthedEditPromptIdRouteImport } from './routes/_authed/edit.$promptId'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const GuessRouteRoute = GuessRouteRouteImport.update({
  id: '/_guess',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const DemoDrizzleRoute = DemoDrizzleRouteImport.update({
  id: '/demo/drizzle',
  path: '/demo/drizzle',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedCreateRoute = AuthedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const GuessAuthRegisterRoute = GuessAuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => GuessRouteRoute,
} as any)
const GuessAuthLoginRoute = GuessAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => GuessRouteRoute,
} as any)
const AuthedViewPromptIdRoute = AuthedViewPromptIdRouteImport.update({
  id: '/view/$promptId',
  path: '/view/$promptId',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedEditPromptIdRoute = AuthedEditPromptIdRouteImport.update({
  id: '/edit/$promptId',
  path: '/edit/$promptId',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/create': typeof AuthedCreateRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/edit/$promptId': typeof AuthedEditPromptIdRoute
  '/view/$promptId': typeof AuthedViewPromptIdRoute
  '/auth/login': typeof GuessAuthLoginRoute
  '/auth/register': typeof GuessAuthRegisterRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedIndexRoute
  '/create': typeof AuthedCreateRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/edit/$promptId': typeof AuthedEditPromptIdRoute
  '/view/$promptId': typeof AuthedViewPromptIdRoute
  '/auth/login': typeof GuessAuthLoginRoute
  '/auth/register': typeof GuessAuthRegisterRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_guess': typeof GuessRouteRouteWithChildren
  '/_authed/create': typeof AuthedCreateRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/edit/$promptId': typeof AuthedEditPromptIdRoute
  '/_authed/view/$promptId': typeof AuthedViewPromptIdRoute
  '/_guess/auth/login': typeof GuessAuthLoginRoute
  '/_guess/auth/register': typeof GuessAuthRegisterRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/demo/drizzle'
    | '/edit/$promptId'
    | '/view/$promptId'
    | '/auth/login'
    | '/auth/register'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/demo/drizzle'
    | '/edit/$promptId'
    | '/view/$promptId'
    | '/auth/login'
    | '/auth/register'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/_authed'
    | '/_guess'
    | '/_authed/create'
    | '/demo/drizzle'
    | '/_authed/'
    | '/_authed/edit/$promptId'
    | '/_authed/view/$promptId'
    | '/_guess/auth/login'
    | '/_guess/auth/register'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  GuessRouteRoute: typeof GuessRouteRouteWithChildren
  DemoDrizzleRoute: typeof DemoDrizzleRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guess': {
      id: '/_guess'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuessRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/demo/drizzle': {
      id: '/demo/drizzle'
      path: '/demo/drizzle'
      fullPath: '/demo/drizzle'
      preLoaderRoute: typeof DemoDrizzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/create': {
      id: '/_authed/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthedCreateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guess/auth/register': {
      id: '/_guess/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof GuessAuthRegisterRouteImport
      parentRoute: typeof GuessRouteRoute
    }
    '/_guess/auth/login': {
      id: '/_guess/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof GuessAuthLoginRouteImport
      parentRoute: typeof GuessRouteRoute
    }
    '/_authed/view/$promptId': {
      id: '/_authed/view/$promptId'
      path: '/view/$promptId'
      fullPath: '/view/$promptId'
      preLoaderRoute: typeof AuthedViewPromptIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/edit/$promptId': {
      id: '/_authed/edit/$promptId'
      path: '/edit/$promptId'
      fullPath: '/edit/$promptId'
      preLoaderRoute: typeof AuthedEditPromptIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedCreateRoute: typeof AuthedCreateRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedEditPromptIdRoute: typeof AuthedEditPromptIdRoute
  AuthedViewPromptIdRoute: typeof AuthedViewPromptIdRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedCreateRoute: AuthedCreateRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedEditPromptIdRoute: AuthedEditPromptIdRoute,
  AuthedViewPromptIdRoute: AuthedViewPromptIdRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface GuessRouteRouteChildren {
  GuessAuthLoginRoute: typeof GuessAuthLoginRoute
  GuessAuthRegisterRoute: typeof GuessAuthRegisterRoute
}

const GuessRouteRouteChildren: GuessRouteRouteChildren = {
  GuessAuthLoginRoute: GuessAuthLoginRoute,
  GuessAuthRegisterRoute: GuessAuthRegisterRoute,
}

const GuessRouteRouteWithChildren = GuessRouteRoute._addFileChildren(
  GuessRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  GuessRouteRoute: GuessRouteRouteWithChildren,
  DemoDrizzleRoute: DemoDrizzleRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
